<?php
/**
 * Render the Tidbits parent block on the front end.
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The rendered inner blocks (morsels).
 * @param WP_Block $block      The block instance.
 *
 * @package Tidbits
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( empty( trim( $content ) ) ) {
	return;
}

$display_mode = $attributes['displayMode'] ?? 'accordion';
$wrapper_attrs = get_block_wrapper_attributes(
	array(
		'class' => 'tidbits tidbits--' . esc_attr( $display_mode ),
	)
);

if ( 'accordion' === $display_mode ) {
	printf(
		'<dl %s data-wp-interactive="tidbits">%s</dl>',
		$wrapper_attrs, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes.
		$content // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Inner block output.
	);
} else {
	printf(
		'<dl %s>%s</dl>',
		$wrapper_attrs, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes.
		$content // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Inner block output.
	);
}
