<?php
/**
 * Render the Tidbits parent block on the front end.
 *
 * @param array    $attributes The block attributes.
 * @param string   $content    The rendered inner blocks (morsels).
 * @param WP_Block $block      The block instance.
 *
 * @package Tidbits
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( empty( trim( $content ) ) ) {
	return;
}

$tidbits_display_mode  = $attributes['displayMode'] ?? 'accordion';
$tidbits_wrapper_attrs = get_block_wrapper_attributes(
	array(
		'class' => 'tidbits tidbits--' . esc_attr( $tidbits_display_mode ),
	)
);

if ( 'accordion' === $tidbits_display_mode ) {
	// Accordion uses the APG disclosure pattern (heading + button + panel), so
	// the wrapper is a <div>; the description list is reserved for the static
	// stacked/columns modes.
	printf(
		'<div %s data-wp-interactive="tidbits">%s</div>',
		$tidbits_wrapper_attrs, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes.
		$content // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Inner block output.
	);
} else {
	printf(
		'<dl %s>%s</dl>',
		$tidbits_wrapper_attrs, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes.
		$content // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Inner block output.
	);
}
